<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EN</name>
   <tag></tag>
   <elementGuidId>9d55dc4d-c01c-4ea2-b0cf-196019bcba7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ant-dropdown-menu-item.ant-dropdown-menu-item-active.ant-dropdown-menu-item-only-child > span.ant-dropdown-menu-title-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div[2]/div[6]/div/div/div/ul/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c4cf741-311f-44fe-b858-ddd58a806b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-dropdown-menu-title-content</value>
      <webElementGuid>5ce0c0a0-4d20-4c34-a2eb-ea84d12eaf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EN</value>
      <webElementGuid>1b8be971-8fc8-47f9-9b90-0cd021b18cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;__2TiPnW7L&quot;]/div[@class=&quot;xQPWLz3L&quot;]/div[@class=&quot;Zwl3czSd&quot;]/div[@class=&quot;_zmV_2_Q&quot;]/div[1]/div[1]/div[@class=&quot;ant-dropdown __1ZBqw1OM ant-dropdown-placement-bottom&quot;]/ul[@class=&quot;ant-dropdown-menu ant-dropdown-menu-root ant-dropdown-menu-vertical ant-dropdown-menu-light&quot;]/li[@class=&quot;ant-dropdown-menu-item ant-dropdown-menu-item-active ant-dropdown-menu-item-only-child&quot;]/span[@class=&quot;ant-dropdown-menu-title-content&quot;]</value>
      <webElementGuid>23784ae2-320c-42cb-ad45-807230367726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div[2]/div[6]/div/div/div/ul/li/span</value>
      <webElementGuid>d2730dd1-fac5-4f03-9680-27724e5da383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::span[1]</value>
      <webElementGuid>1f4faf1a-99f5-4334-993c-185727c65a66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gabung Bersama Kami'])[1]/following::span[2]</value>
      <webElementGuid>3ef9f34f-6ce2-43df-8585-8574236b3431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[2]/preceding::span[2]</value>
      <webElementGuid>72c7a63c-ef2a-48a6-90dd-e78f675ed224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/ul/li/span</value>
      <webElementGuid>0a5d474e-ba18-481f-8f36-4d22bae452cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'EN' or . = 'EN')]</value>
      <webElementGuid>47f5cde6-dfc4-4f41-b0c0-9362c5b1cd9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
